// This module wraps the generated OpenNext worker with Cloudflare scheduled events.
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- The generated module may exist locally but is absent in a clean checkout.
// @ts-ignore Generated by `npm run cfbuild` before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";

interface WorkerSelfReference {
  fetch(request: Request): Promise<Response>;
}

interface TradePilotWorkerEnv {
  WORKER_SELF_REFERENCE: WorkerSelfReference;
  TRADEPILOT_CRON_SECRET?: string;
}

interface WorkerExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
}

interface ScheduledController {
  cron: string;
  scheduledTime: number;
}

async function runEmailOutbox(env: TradePilotWorkerEnv) {
  const secret = env.TRADEPILOT_CRON_SECRET?.trim();
  if (!secret) throw new Error("TRADEPILOT_CRON_SECRET is not configured");
  const response = await env.WORKER_SELF_REFERENCE.fetch(new Request(
    "https://tradepilot.internal/api/internal/email/outbox",
    { method: "POST", headers: { Authorization: `Bearer ${secret}` } },
  ));
  if (!response.ok) throw new Error(`Email outbox schedule failed with status ${response.status}`);
}

const worker = {
  fetch: openNextWorker.fetch,
  scheduled(_controller: ScheduledController, env: TradePilotWorkerEnv, context: WorkerExecutionContext) {
    context.waitUntil(runEmailOutbox(env));
  },
};

export default worker;
