import assert from "node:assert/strict";
import test from "node:test";
import { createMemoryPaymentRepository } from "../../src/lib/payments/repository";
import { applyPaymentEvent, createPaymentAccount, createPaymentRequest, getPublicPayment, startPayment, createRefund } from "../../src/lib/payments/service";
import type { PaymentProviderAdapter } from "../../src/lib/payments/types";

const COMPANY = "10000000-0000-4000-8000-000000000001";
const USER = "10000000-0000-4000-8000-000000000002";
const ORDER = "10000000-0000-4000-8000-000000000003";
const KEY = Buffer.alloc(32, 7).toString("base64url");

function adapter(): PaymentProviderAdapter {
  return { async createCheckout() { return { providerTransactionId: "pi_1", paymentUrl: "https://pay.example/1" }; }, async verifyWebhook() { return []; }, async refund() { return { providerRefundId: "re_1" }; } };
}

test("payment requests enforce order balance and expose only public fields", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-1", totalAmount: "100.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });
  const account = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe", credentials: { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" } }, KEY);
  assert.equal(account.credentialsConfigured, true);
  const result = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "30.00", currency: "USD" });
  const publicView = await getPublicPayment(repository, result.token);
  assert.equal(publicView?.amountMinor, 3000);
  assert.equal("companyId" in (publicView || {}), false);
  assert.equal("publicTokenHash" in (publicView || {}), false);
  await assert.rejects(() => createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "101.00", currency: "USD" }), /exceeds/i);
  let checkoutUrl = "";
  const checkoutAdapter = adapter();
  checkoutAdapter.createCheckout = async (input) => {
    checkoutUrl = input.successUrl;
    return { providerTransactionId: "pi_1", paymentUrl: "https://pay.example/1" };
  };
  const attempt = await startPayment(repository, { request: result.request, publicToken: result.token, account, adapter: checkoutAdapter, idempotencyKey: "attempt-1", baseUrl: "https://tradepilot.example" });
  assert.equal(attempt?.status, "requires_action");
  assert.equal(checkoutUrl, `https://tradepilot.example/pay/${result.token}`);
  assert.equal(checkoutUrl.includes(result.request.publicTokenHash), false);
  const same = await startPayment(repository, { request: result.request, publicToken: result.token, account, adapter: adapter(), idempotencyKey: "attempt-1", baseUrl: "https://tradepilot.example" });
  assert.equal(same?.id, attempt?.id);
});

test("pending payment requests reserve order balance before an attempt exists", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-PENDING", totalAmount: "100.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });

  await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "60.00", currency: "USD" });

  await assert.rejects(
    () => createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "50.00", currency: "USD" }),
    /exceeds/i,
  );
});

test("payment account webhook identifiers are generated by the server", async () => {
  const repository = createMemoryPaymentRepository();
  const credentials = { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" };
  const first = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe", publicAccountId: "shared-public-id", credentials }, KEY);
  const second = await createPaymentAccount(repository, "20000000-0000-4000-8000-000000000001", { provider: "stripe", displayName: "Stripe 2", publicAccountId: "shared-public-id", credentials }, KEY);

  assert.notEqual(first.publicAccountId, "shared-public-id");
  assert.notEqual(second.publicAccountId, "shared-public-id");
  assert.notEqual(first.publicAccountId, second.publicAccountId);
});

test("active payment attempts are scoped to the selected payment account", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-ACCOUNT", totalAmount: "100.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });
  const credentials = { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" };
  const firstAccount = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe A", credentials }, KEY);
  const secondAccount = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe B", credentials }, KEY);
  const request = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "10.00", currency: "USD" });
  const first = await startPayment(repository, { request: request.request, publicToken: request.token, account: firstAccount, adapter: adapter(), idempotencyKey: "account-a", baseUrl: "https://tradepilot.example" });
  let secondCheckoutCreated = false;
  const secondAdapter = adapter();
  secondAdapter.createCheckout = async () => {
    secondCheckoutCreated = true;
    return { providerTransactionId: "pi_2", paymentUrl: "https://pay.example/2" };
  };

  const second = await startPayment(repository, { request: request.request, publicToken: request.token, account: secondAccount, adapter: secondAdapter, idempotencyKey: "account-b", baseUrl: "https://tradepilot.example" });

  assert.equal(secondCheckoutCreated, true);
  assert.notEqual(second.id, first.id);
  assert.equal(second.paymentAccountId, secondAccount.id);
});

test("idempotency keys cannot return an attempt from another payment request", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-IDEMPOTENCY", totalAmount: "100.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });
  const account = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe", credentials: { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" } }, KEY);
  const firstRequest = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "10.00", currency: "USD" });
  const secondRequest = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "10.00", currency: "USD" });
  await startPayment(repository, { request: firstRequest.request, publicToken: firstRequest.token, account, adapter: adapter(), idempotencyKey: "shared-idempotency-key", baseUrl: "https://tradepilot.example" });

  await assert.rejects(
    () => startPayment(repository, { request: secondRequest.request, publicToken: secondRequest.token, account, adapter: adapter(), idempotencyKey: "shared-idempotency-key", baseUrl: "https://tradepilot.example" }),
    /idempotency key does not match/i,
  );
});

test("verified payment events must match provider, amount, currency, and order", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-EVENT", totalAmount: "100.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });
  const account = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe", credentials: { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" } }, KEY);
  const request = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "10.00", currency: "USD" });
  const attempt = await startPayment(repository, { request: request.request, publicToken: request.token, account, adapter: adapter(), idempotencyKey: "attempt-event", baseUrl: "https://tradepilot.example" });

  const baseEvent = { providerEventId: "evt-mismatch", kind: "payment_succeeded" as const, attemptId: attempt!.id, providerTransactionId: "pi_event", amountMinor: 1000, currency: "USD", orderReference: "SO-EVENT" };
  await assert.rejects(() => applyPaymentEvent(repository, baseEvent, { companyId: COMPANY, requestId: request.request.id, provider: "alipay" }), /provider/i);
  await assert.rejects(() => applyPaymentEvent(repository, { ...baseEvent, providerEventId: "evt-amount", amountMinor: 999 }, { companyId: COMPANY, requestId: request.request.id, provider: "stripe" }), /amount/i);
  await assert.rejects(() => applyPaymentEvent(repository, { ...baseEvent, providerEventId: "evt-currency", currency: "CNY" }, { companyId: COMPANY, requestId: request.request.id, provider: "stripe" }), /currency/i);
  await assert.rejects(() => applyPaymentEvent(repository, { ...baseEvent, providerEventId: "evt-order", orderReference: "SO-OTHER" }, { companyId: COMPANY, requestId: request.request.id, provider: "stripe" }), /order/i);
  await assert.rejects(() => applyPaymentEvent(repository, { ...baseEvent, providerEventId: "evt-missing-amount", amountMinor: undefined }, { companyId: COMPANY, requestId: request.request.id, provider: "stripe" }), /amount/i);
});

test("refunds cannot exceed paid attempt amount", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-2", totalAmount: "100.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });
  const account = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe", credentials: { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" } }, KEY);
  const request = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "10.00", currency: "USD" });
  const attempt = await startPayment(repository, { request: request.request, publicToken: request.token, account, adapter: adapter(), idempotencyKey: "attempt-refund", baseUrl: "https://tradepilot.example" });
  await repository.updateAttempt(COMPANY, attempt!.id, { status: "paid", providerTransactionId: "pi_1" });
  const refund = await createRefund(repository, { companyId: COMPANY, userId: USER, requestId: request.request.id, attemptId: attempt!.id, amountMinor: 500, reason: "test", idempotencyKey: "refund-1", adapter: adapter() });
  assert.equal(refund?.status, "succeeded");
  await assert.rejects(() => createRefund(repository, { companyId: COMPANY, userId: USER, requestId: request.request.id, attemptId: attempt!.id, amountMinor: 600, reason: "test", idempotencyKey: "refund-2", adapter: adapter() }), /exceeds/i);
});

test("refund webhook events update the matching refund and order balance", async () => {
  const repository = createMemoryPaymentRepository();
  repository.seedOrder({ id: ORDER, companyId: COMPANY, orderNo: "SO-REFUND-EVENT", totalAmount: "10.00", currency: "USD", paymentStatus: "unpaid", amountPaidMinor: 0, merchantName: "Demo" });
  const account = await createPaymentAccount(repository, COMPANY, { provider: "stripe", displayName: "Stripe", credentials: { secretKey: "sk_test", publishableKey: "pk_test", webhookSecret: "whsec_test" } }, KEY);
  const request = await createPaymentRequest(repository, { companyId: COMPANY, userId: USER, orderId: ORDER, amount: "10.00", currency: "USD" });
  const attempt = await startPayment(repository, { request: request.request, publicToken: request.token, account, adapter: adapter(), idempotencyKey: "refund-event-attempt", baseUrl: "https://tradepilot.example" });
  await repository.updateAttempt(COMPANY, attempt.id, { status: "paid", providerTransactionId: "pi_refund_event" });
  await repository.updateOrderPayment(COMPANY, ORDER, "paid", 1000);
  const pendingRefund = await repository.createRefund({ id: "10000000-0000-4000-8000-000000000099", companyId: COMPANY, requestId: request.request.id, attemptId: attempt.id, amountMinor: 500, reason: "event test", providerRefundId: "re_event", status: "pending", idempotencyKey: "refund-event", createdBy: USER, createdAt: new Date(0).toISOString(), updatedAt: new Date(0).toISOString() });

  await applyPaymentEvent(repository, { providerEventId: "evt-refund", kind: "refund_succeeded", providerTransactionId: "pi_refund_event", refundId: "re_event", refundAmountMinor: 500 }, { companyId: COMPANY, provider: "stripe" });

  const storedRefund = (await repository.listRefunds(COMPANY, request.request.id)).find((item) => item.id === pendingRefund.id);
  const order = await repository.getOrder(COMPANY, ORDER);
  assert.equal(storedRefund?.status, "succeeded");
  assert.equal(order?.paymentStatus, "partially_refunded");
  assert.equal(order?.amountPaidMinor, 500);
});
